server:
  port: 8095

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true



  datasource:
    url: jdbc:postgresql://localhost:5432/gym_bd
    username: postgres
    password: nikucha666
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

services:
  gym:
    url: 'http://localhost:8091/api/v1'
  workload:
    url: 'http://localhost:8092/api/v1/trainer/workload'

feign:
  client:
    config:
      domain:
        connectTimeout: 5000
        readTimeout: 3000
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    upskill.logger: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
