server:
  port: 8095

spring:
  application:
    name: gateway-service

  cloud:
    loadbalancer:
      ribbon:
        enabled: false

      sleuth:
        sampler:
          probability: 1.0

      zipkin:
        base-url: http://127.0.0.1:9411/
logging:
  level:
    com.netflix.loadbalancer: DEBUG
    upskill.logger: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

#secret: "SECRET"
jwt:
  secret: 111111111111122222222222222224444444444444444444444444444444444444tyutghfcjdecuijednklfcmedfbdsziokplfhivokfplddcgdvgcvdduhvuifmklvmdklmvkfhgvuihfuid8

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://127.0.0.1:8761/eureka}
  instance:
    hostname: 127.0.0.1
    preferIpAddress: false


