server:
  port: 8091

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gym_bd
    username: postgres
    password: nikucha666
    driver-class-name: org.postgresql.Driver
    schema: gym_schema

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop

hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  hbm2ddl.auto: update

logging:
  level:
    org.hibernate.SQL: DEBUG
    com.epam.upskill.logger: DEBUG
