server:
  port: 8091

spring:
  config:
    activate:
      on-profile: default
  datasource:
    url: jdbc:postgresql://localhost:5432/gym_bd
    username: postgres
    password: nikucha666
    driver-class-name: org.postgresql.Driver
    schema: gym_schema

  jpa:
    show-sql: true

hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  hbm2ddl.auto: update

logging:
  level:
    org.hibernate.SQL: DEBUG
    com.epam.upskill.logger: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
  metrics:
    export:
      prometheus:
        enabled: true
    endpoint:
      metrics:
        enabled: true

