server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/название_базы_данных
    username: ваше_имя_пользователя
    password: ваш_пароль
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect