server:
  port: 8091

spring:
  application:
    name: gym-service
  config:
    activate:
      on-profile: default
  datasource:
    url: jdbc:postgresql://localhost:5432/gym_bd
    username: postgres
    password: nikucha666
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  sleuth:
    sampler:
      probability: 1.0
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  zipkin:
    base-url: http://127.0.0.1:9411/


hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  hbm2ddl.auto: update

logging:
  level:
    org.hibernate.SQL: DEBUG
#    upskill.logger: DEBUG
#    org.springframework.web: DEBUG
    org.springframework.amqp: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

  metrics:
    export:
      prometheus:
        enabled: true
    endpoint:
      metrics:
        enabled: true

secret: "SECRET"

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://127.0.0.1:8761/eureka}
  instance:
    hostname: 127.0.0.1
    preferIpAddress: false

