server:
  port: 8091

spring:
  application:
    name: gym
  config:
    activate:
      on-profile: default
  datasource:
    url: jdbc:postgresql://localhost:5432/gym_bd
    username: postgres
    password: nikucha666
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true

hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  hbm2ddl.auto: update

logging:
  level:
    org.hibernate.SQL: DEBUG
    upskill.logger: DEBUG
    org.springframework.web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
  metrics:
    export:
      prometheus:
        enabled: true
    endpoint:
      metrics:
        enabled: true

secret: "SECRET"

feign:
  client:
    config:
      domain:
        connectTimeout: 5000
        readTimeout: 3000

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true