server:
  port: 8092

spring:
  application:
    name: workload-service

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  h2:
    console:
      enabled: true
      path: /h2-console
  sleuth:
    sampler:
      probability: 1.0

  zipkin:
    base-url: http://127.0.0.1:9411/

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  level:
    org.hibernate.SQL: DEBUG
    upskill.logger: DEBUG
    org.springframework.amqp: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://127.0.0.1:8761/eureka}
  instance:
    hostname: 127.0.0.1
    preferIpAddress: false
ribbon:
  eureka:
    enabled: true

