server:
  port: 8092

spring:
  application:
    name: workload-service
  #
  #  config:
  #    activate:
  #      on-profile: default

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.hibernate.SQL: DEBUG
    upskill.logger: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://127.0.0.1:8761/eureka}
  instance:
    hostname: 127.0.0.1
    preferIpAddress: false
ribbon:
  eureka:
    enabled: true
#feign:
#  client:
#    config:
#      domain:
#        connectTimeout: 5000
#        readTimeout: 3000