server:
  port: 8092

spring:
  application:
    name: workload-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: TrainerTrainings
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

  sleuth:
    sampler:
      probability: 1.0

  zipkin:
    base-url: http://127.0.0.1:9411/

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  level:
    org.hibernate.SQL: DEBUG
    upskill.logger: DEBUG
    org.springframework.amqp: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://127.0.0.1:8761/eureka}
  instance:
    hostname: 127.0.0.1
    preferIpAddress: false
ribbon:
  eureka:
    enabled: true
